FROM python:3.11-slim-bookworm

# Do not generate .pyc files and enable stdout buffering
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install only required system dependencies
# ffmpeg: needed by pydub for audio
# libpq-dev: needed by psycopg2
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ffmpeg \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy code
COPY backend/ ./backend/
COPY src/ ./src/

EXPOSE 8000

# /app/backend/app.py is the location of FastAPI app
CMD ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]




# Build from root: docker build -t fastapi-backend -f backend/Dockerfile.fastapi .
# Run with .env: docker run -p 8000:8000 --env-file .env fastapi-backend
