FROM python:3.12-slim

# Do not generate .pyc files and enable stdout buffering
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1



# Set working directory
WORKDIR /app


# Install system dependencies needed for psycopg2
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*



# Copy only requirements from backend folder
COPY backend/requirements.txt ./backend/


RUN pip install  -r backend/requirements.txt

# Copy code part
COPY backend/ ./backend/
COPY src/ ./src/

EXPOSE 8000

# /app/backend/app.py is the location of FastAPI app
CMD ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]




# we are building from root directery
# docker build -t fastapi-backend -f backend/Dockerfile.fastapi .


#to run with .env
# docker run -p 8000:8000 --env-file .env fastapi-backend
